# -*- coding: utf-8 -*-
"""Spyware_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-tWB6RHRUC-ia5TS5nf5SSM1Wk8SVUIf
"""

# ============================================================
# Spyware Detection using Deep Neural Network (MLP)
# MalMem2022 Dataset
# ============================================================

# ============================================================
# STEP 0: Install & Import Libraries
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import joblib

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (confusion_matrix, classification_report,
                             accuracy_score, recall_score,
                             f1_score, precision_score)

print("TensorFlow version:", tf.__version__)

# ============================================================
# STEP 1: Upload Dataset
# ============================================================
# Run this cell to upload MalMem2022.csv from your computer
import os

# ضعي بياناتك هنا مباشرة
os.environ['KAGGLE_USERNAME'] = 'reemissasaleh'
os.environ['KAGGLE_KEY'] = 'KGAT_f74b39828290000290c2ed2ce53e0f84'

# تحميل الداتاسيت
!pip install kaggle -q
!kaggle datasets download -d luccagodoy/obfuscated-malware-memory-2022-cic
!unzip -q obfuscated-malware-memory-2022-cic.zip
!ls

import pandas as pd
df = pd.read_csv('Obfuscated-MalMem2022.csv')
print(df.shape)
print(df.head())

# ============================================================
# STEP 2: Data Preprocessing
# ============================================================
df = pd.read_csv('Obfuscated-MalMem2022.csv')

print("Dataset Shape:", df.shape)
print("\nColumn Names:", df.columns.tolist())
print("\nClass Distribution:\n", df['Class'].value_counts())
print("\nCategory Distribution:\n", df['Category'].value_counts())

# Remove duplicates
initial_len = len(df)
df.drop_duplicates(inplace=True)
print(f"\nRemoved {initial_len - len(df)} duplicates.")

# Check missing values
print("\nMissing Values:", df.isnull().sum().sum())

# Statistical Analysis
stats = df.describe().transpose()[['min', 'max', 'mean', 'std']]
print("\nStatistical Analysis (First 10 features):\n", stats.head(10))

# Visualize class distribution
plt.figure(figsize=(10, 6))
sns.countplot(x='Class', data=df)
plt.title('Class Distribution (Benign vs Malicious)')
plt.savefig('class_distribution.png')
plt.show()

# ============================================================
# STEP 3: Feature Engineering & Splitting (Modified)
# ============================================================

# حذف الأعمدة التي قد تسبب Data Leakage
leakage_columns = [
    'Class',
    'Category',
    'Label',
    'Malware',
    'Family'
]

X = df.drop(columns=[col for col in leakage_columns if col in df.columns])
y = df['Class']


# Encode labels
le = LabelEncoder()
y = le.fit_transform(y)

joblib.dump(le, 'label_encoder.pkl')


# Split first
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)


# Scaling after split
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)


joblib.dump(scaler, 'scaler.pkl')


print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

# ============================================================
# STEP 4: Build & Train Model
# ============================================================
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.2),

    Dense(32, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),

    Dense(16, activation='relu'),
    BatchNormalization(),

    Dense(1, activation='sigmoid')
])

optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer,
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

EPOCHS = 20
BATCH_SIZE = 64

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    verbose=1
)

model.save('spyware_detector_model.keras')
print("\nModel saved!")

# Plot training history
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Val Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.savefig('training_history.png')
plt.show()

# ============================================================
# STEP 5: Evaluate Model
# ============================================================
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)

accuracy  = accuracy_score(y_test, y_pred)
recall    = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
f1        = f1_score(y_test, y_pred)

print(f"Accuracy:  {accuracy:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"Precision: {precision:.4f}")
print(f"F1-score:  {f1:.4f}")
print("\nClassification Report:\n",
      classification_report(y_test, y_pred,
                            target_names=['Benign', 'Malware']))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benign', 'Malware'],
            yticklabels=['Benign', 'Malware'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.savefig('confusion_matrix.png')
plt.show()

# ============================================================
# STEP 6: Predict on a Sample
# ============================================================
def predict_sample(sample_data):
    sample_scaled = scaler.transform(sample_data)
    prediction_prob = model.predict(sample_scaled)
    prediction_class = (prediction_prob > 0.5).astype(int)
    class_name = le.inverse_transform(prediction_class[0])[0]
    confidence = (prediction_prob[0][0]
                  if prediction_class[0][0] == 1
                  else 1 - prediction_prob[0][0])
    return class_name, confidence

# Test with first sample
sample_raw = df.drop(columns=['Class', 'Category']).iloc[0:1]
class_name, confidence = predict_sample(sample_raw)

print(f"Sample Prediction: {class_name}")
print(f"Confidence: {confidence*100:.2f}%")
print(f"Actual Class: {'Malware' if y_test[0] == 1 else 'Benign'}")